env:
  browser: true
  es2021: true
  webextensions: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: 12
rules:
  no-var: warn
  no-unused-vars: warn
